function createfigure1(cdata1,titulo)
%CREATEFIGURE1(CDATA1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 04-Nov-2017 00:38:24

% Create figure
figure1 = figure;set(figure1, 'Visible', 'off');

% Create axes
axes1 = axes('Parent',figure1,'Layer','top','YDir','reverse');
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.5 128.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.5 128.5]);
box(axes1,'on');
hold(axes1,'on');
axis off

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

% Create title
title({titulo});

saveas(figure1,strcat('figures/',titulo,'.png'));

